# Generated by Django 5.1.1 on 2024-09-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_project_backend_technologies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
